name: Continuous integration

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

defaults:
  run:
    shell: bash

jobs:
  vectorscan:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Linux dependencies
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          sudo apt-get update
          sudo apt-get install -yq cmake clang
      - name: Install MacOS dependencies
        if: startsWith(matrix.os, 'macos-')
        run: |
          brew install cmake
      - name: Build
        run: |
          mkdir build
          cd build
          cmake \
            ../ \
            -DBUILD_STATIC_LIBS=on \
            -DPCRE_BUILD_SOURCE=on \
            -DCMAKE_CXX_FLAGS='-Wno-unqualified-std-cast-call' \
            -DCMAKE_BUILD_TYPE=Release
          make install DESTDIR=./tmp
      - name: Push artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "vectorscan"
          path: "./tmp"
 
  golangci:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -yq libhyperscan-dev libpcap-dev

      - uses: actions/setup-go@v3

      - uses: actions/checkout@v3

      # - name: golangci-lint
      #   uses: golangci/golangci-lint-action@v3
      #   with:
      #     version: latest
      #     working-directory: hyperscan
