name: Continuous integration

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

defaults:
  run:
    shell: bash

jobs:
  vectorscan:
    strategy:
      matrix:
        include:
          - os: linux
            arch: arm64
            runner: ubuntu-22.04
          - os: linux
            arch: amd64
            runner: ubuntu-22.04
          # - os: darwin
          #   arch: arm64
          #   runner: ubuntu-22.04
          # - os: darwin
          #   arch: amd64
          #   runner: ubuntu-22.04
          - os: windows
            arch: amd64
            runner: ubuntu-22.04
            
    runs-on: ${{ matrix.runner }}
    env:
      GOOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -yq cmake ragel libpcap-dev
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0-dev.3541+05b185811

      - name: Build
        run: |
          ./build.sh

      # - name: Install Golang 1.21.1
      #   uses: actions/setup-go@v4
      #   with:
      #     go-version: 1.21.1
      # - name: Test
      #   run: |
      #     go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
 
  golangci:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -yq libhyperscan-dev libpcap-dev

      - uses: actions/setup-go@v3

      - uses: actions/checkout@v3

      # - name: golangci-lint
      #   uses: golangci/golangci-lint-action@v3
      #   with:
      #     version: latest
      #     working-directory: hyperscan
